name: google_weather_flutter
description: A comprehensive Flutter plugin for the Google Weather API. Easily fetch current conditions, hourly and daily forecasts, and historical weather data for your apps.
version: 0.1.2
homepage: https://github.com/oscarshaitan/google_weather_api

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  test: ^1.25.2

flutter:
  uses-material-design: true
