name: google_weather_flutter
description: A Flutter plugin for the Google Weather API.
version: 0.0.1
homepage: https://github.com/your-username/google_weather_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  test: ^1.24.3

flutter:
  uses-material-design: true
